spring:
  datasource:
    driver-class-name:
    url:
    username:
    password:
  redis:
    host:
    port:
    database:
    jedis:
      pool:
        min-idle:
        max-wait:
        max-active:
        max-idle:
  mail:
    host:
    port:
    username:
    password:
    from:
    to:

logging:
  config:
  level:
    org.springframework.web:
    com.github.binarywang.demo.wx.mp:
    me.zhiyao.faintecho:

wx:
  mp:
    app-id:
    secret:
    token:
    aes-key:
    config-storage:
      type:
      redis:
        host:
        port:
      http-client-type:

qweather:
  key:

chevereto:
  key:

tencent:
  appId:
  appKey:
